Repository CDCgov/prime-simplereport, pull requests merged in 2021-05, with the labels that each got.

#1494 Update terraform to version 0.15.1.
  .github/workflows/deployDemo.yml
  .github/workflows/deployDev.yml
  .github/workflows/deployPentest.yml
  .github/workflows/deployProd.yml
  .github/workflows/deployStg.yml
  .github/workflows/deployTest.yml
  .github/workflows/deployTraining.yml
  .github/workflows/terraform_checks.yml
Labels: DevOps

#1497 Import "Everyone" group into global configuration.
  ops/global/_data.tf
  ops/global/main.tf
  ops/services/okta-global/_var.tf
  ops/services/okta-global/main.tf
Labels: DevOps

#1484 Add error states and validation for account creation components
  frontend/.storybook/main.js
  frontend/package.json
  frontend/src/app/accountCreation/MfaSelect/MfaSelect.test.tsx
  frontend/src/app/accountCreation/MfaSelect/MfaSelect.tsx
  frontend/src/app/accountCreation/MfaSms/MfaSms.stories.tsx
  frontend/src/app/accountCreation/MfaSms/MfaSms.test.tsx
  frontend/src/app/accountCreation/MfaSms/MfaSms.tsx
  frontend/src/app/accountCreation/MfaSmsVerify/MfaSmsVerify.stories.tsx
  frontend/src/app/accountCreation/MfaSmsVerify/MfaSmsVerify.test.tsx
  frontend/src/app/accountCreation/MfaSmsVerify/MfaSmsVerify.tsx
  frontend/src/app/accountCreation/PasswordForm/PasswordForm.stories.tsx
  frontend/src/app/accountCreation/PasswordForm/PasswordForm.test.tsx
  frontend/src/app/accountCreation/PasswordForm/PasswordForm.tsx
  frontend/src/app/accountCreation/SecurityQuestion/SecurityQuestion.test.tsx
  frontend/src/app/accountCreation/SecurityQuestion/SecurityQuestion.tsx
  frontend/src/app/patients/personSchema.ts
  frontend/src/app/utils/text.ts
  frontend/yarn.lock
Labels: Growth & Engagement

#1501 Add button story to Storybook
  frontend/src/app/Settings/Facility/Components/ManageDevices.tsx
  frontend/src/app/Settings/Facility/FacilityForm.tsx
  frontend/src/app/Settings/ManageOrganization.tsx
  frontend/src/app/Settings/Settings.tsx
  frontend/src/app/Settings/Users/CreateUserForm.tsx
  frontend/src/app/Settings/Users/DeleteUserModal.tsx
  frontend/src/app/Settings/Users/InProgressModal.tsx
  frontend/src/app/Settings/Users/ManageUsers.tsx
  frontend/src/app/Settings/Users/UserFacilitiesSettingsForm.tsx
  frontend/src/app/accountCreation/MfaComplete/MfaComplete.tsx
  frontend/src/app/accountCreation/MfaSelect/MfaSelect.tsx
  frontend/src/app/accountCreation/MfaSms/MfaSms.tsx
  frontend/src/app/accountCreation/MfaSmsVerify/MfaSmsVerify.tsx
  frontend/src/app/accountCreation/PasswordForm/PasswordForm.tsx
  frontend/src/app/accountCreation/SecurityQuestion/SecurityQuestion.tsx
  frontend/src/app/admin/DeviceType/DeviceTypeForm.tsx
  frontend/src/app/admin/Organization/OrganizationForm.tsx
  frontend/src/app/admin/Organization/PendingOrganizationsList.tsx
  frontend/src/app/commonComponents/AddressConfirmationModal.tsx
  frontend/src/app/commonComponents/Button/Button.stories.tsx
  frontend/src/app/commonComponents/Button/Button.tsx
  frontend/src/app/commonComponents/Card/Card.stories.tsx
  frontend/src/app/commonComponents/CardBackground/CardBackground.stories.tsx
  frontend/src/app/commonComponents/CardContainer/CardContainer.stories.tsx
  frontend/src/app/commonComponents/Header.tsx
  frontend/src/app/commonComponents/TrainingNotification.tsx
  frontend/src/app/facilitySelect/FacilitySelect.tsx
  frontend/src/app/patients/AddPatient.tsx
  frontend/src/app/patients/ArchivePersonModal.tsx
  frontend/src/app/patients/EditPatient.tsx
  frontend/src/app/patients/ManagePatients.tsx
  frontend/src/app/testQueue/AoEForm/AoEForm.tsx
  frontend/src/app/testQueue/AoEForm/AoEModalForm.tsx
  frontend/src/app/testQueue/QueueItem.tsx
  frontend/src/app/testQueue/addToQueue/SearchResults.tsx
  frontend/src/app/testResults/TestResultCorrectionModal.tsx
  frontend/src/app/testResults/TestResultInputForm.tsx
  frontend/src/app/testResults/TestResultPrintModal.tsx
  frontend/src/app/testResults/TestResultsList.tsx
  frontend/src/patientApp/timeOfTest/DOB.tsx
  frontend/src/patientApp/timeOfTest/PatientFormContainer.tsx
  frontend/src/patientApp/timeOfTest/PatientProfileContainer.tsx
  frontend/src/patientApp/timeOfTest/TermsOfService.tsx
Labels: Growth & Engagement

#1502 Add instructions to revert a release
  README.md
Labels: DevOps

#1153 Terraform changes for PII-restricted Metabase
  ops/prod/_data.tf
  ops/prod/metabase.tf
  ops/services/app_service/metabase/_var.tf
  ops/services/app_service/metabase/main.tf
  ops/services/app_service/metabase/nophi_user.tf
  ops/services/postgres_db/nophi_user.tf
  ops/test/_data.tf
  ops/test/metabase.tf
Labels: DevOps

#1517 Add text input story
  frontend/src/app/commonComponents/Dropdown.tsx
  frontend/src/app/commonComponents/TextInput.tsx
  frontend/src/stories/TextInput.stories.tsx
Labels: Growth & Engagement

#1519 Update error message copy on password form
  frontend/src/app/accountCreation/PasswordForm/PasswordForm.test.tsx
  frontend/src/app/accountCreation/PasswordForm/PasswordForm.tsx
Labels: Growth & Engagement

#1562 Add step indicator story
  frontend/.storybook/preview.js
  frontend/src/stories/StepIndicator.stories.tsx
Labels: Growth & Engagement

#1560 Add Dropdown story
  frontend/src/stories/Dropdown.stories.tsx
Labels: Growth & Engagement

#1500 Terraform pagerduty support
  ops/demo/alerts.tf
  ops/dev/alerts.tf
  ops/global/_config.tf
  ops/global/_output.tf
  ops/global/main.tf
  ops/prod/alerts.tf
  ops/services/alerts/app_service_metrics/_var.tf
  ops/services/alerts/app_service_metrics/main.tf
  ops/services/pagerduty/_data.tf
  ops/services/pagerduty/_outputs.tf
  ops/services/pagerduty/_var.tf
  ops/services/pagerduty/main.tf
  ops/services/pagerduty/versions.tf
  ops/stg/alerts.tf
  ops/test/alerts.tf
  ops/training/alerts.tf
Labels: DevOps

#1504 Terraform upgrade cleanup
  ops/demo/persistent/_config.tf
  ops/dev/persistent/_config.tf
  ops/pentest/_config.tf
  ops/pentest/persistent/_config.tf
  ops/prod/_config.tf
  ops/prod/persistent/_config.tf
  ops/services/okta-app/versions.tf
  ops/services/okta-global/versions.tf
  ops/stg/_config.tf
  ops/stg/persistent/_config.tf
  ops/test/_config.tf
  ops/test/persistent/_config.tf
  ops/training/_config.tf
  ops/training/persistent/_config.tf
Labels: DevOps

#1536 Create organization on user signup
  backend/src/main/java/gov/cdc/usds/simplereport/api/CurrentAccountRequestContextHolder.java
  backend/src/main/java/gov/cdc/usds/simplereport/api/accountrequest/AccountRequestController.java
  backend/src/main/java/gov/cdc/usds/simplereport/api/apiuser/UserMutationResolver.java
  backend/src/main/java/gov/cdc/usds/simplereport/api/model/accountrequest/AccountRequest.java
  backend/src/main/java/gov/cdc/usds/simplereport/api/organization/OrganizationMutationResolver.java
  backend/src/main/java/gov/cdc/usds/simplereport/config/authorization/UserAuthorizationVerifier.java
  backend/src/main/java/gov/cdc/usds/simplereport/idp/repository/DemoOktaRepository.java
  backend/src/main/java/gov/cdc/usds/simplereport/idp/repository/LiveOktaRepository.java
  backend/src/main/java/gov/cdc/usds/simplereport/idp/repository/OktaRepository.java
  backend/src/main/java/gov/cdc/usds/simplereport/service/ApiUserService.java
  backend/src/main/java/gov/cdc/usds/simplereport/service/OrganizationInitializingService.java
  backend/src/main/java/gov/cdc/usds/simplereport/service/OrganizationService.java
  backend/src/main/resources/templates/account-request.html
  backend/src/test/java/gov/cdc/usds/simplereport/api/AccountRequestControllerTest.java
  backend/src/test/java/gov/cdc/usds/simplereport/api/graphql/ApiUserManagementTest.java
  backend/src/test/java/gov/cdc/usds/simplereport/db/repository/TestOrderRepositoryTest.java
  backend/src/test/java/gov/cdc/usds/simplereport/idp/repository/DemoOktaRepositoryTest.java
  backend/src/test/java/gov/cdc/usds/simplereport/service/OrganizationServiceTest.java
  backend/src/test/java/gov/cdc/usds/simplereport/test_util/SliceTestConfiguration.java
  backend/src/test/java/gov/cdc/usds/simplereport/test_util/TestDataFactory.java
Labels: Growth & Engagement

#1658 Tweaked metric alert thresholds in test.
  ops/test/alerts.tf
Labels: DevOps

#1637 Add CLIA number validation to facility form
  frontend/src/app/Settings/Facility/facilitySchema.ts
  frontend/src/app/Settings/FacilityForm.test.tsx
  frontend/src/app/admin/Organization/OrganizationForm.test.tsx
  frontend/src/app/utils/clia.test.ts
  frontend/src/app/utils/clia.ts
  frontend/src/config/constants.ts
Labels: Better Data

#1662 Test results filter drawer stays open when filter is applied
  frontend/src/app/commonComponents/QueryWrapper.tsx
  frontend/src/app/testResults/TestResultsList.test.tsx
  frontend/src/app/testResults/TestResultsList.tsx
Labels: Better Data

#1487 Use Chromatic to deploy Storybook
  .github/workflows/chromatic.yml
  README.md
  frontend/.gitignore
  frontend/package.json
  frontend/yarn.lock
Labels: Growth & Engagement

#1586 📅 Update default date picker with USWDS date picker
  frontend/src/app/testQueue/AoEForm/PriorTestInputs.tsx
  frontend/src/app/testQueue/AoEForm/SymptomInputs.test.tsx
  frontend/src/app/testQueue/AoEForm/SymptomInputs.tsx
  frontend/src/app/testQueue/AoEForm/__snapshots__/PriorTestInputs.test.tsx.snap
  frontend/src/app/testQueue/AoEForm/__snapshots__/SymptomInputs.test.tsx.snap
  frontend/src/app/testQueue/QueueItem.scss
  frontend/src/app/testQueue/QueueItem.test.tsx
  frontend/src/app/testQueue/QueueItem.tsx
  frontend/src/app/testQueue/__snapshots__/QueueItem.test.tsx.snap
  frontend/src/app/testQueue/__snapshots__/TestQueue.test.tsx.snap
  frontend/src/patientApp/timeOfTest/__snapshots__/AoEPatientFormContainer.test.tsx.snap
  frontend/src/scss/PrimeStyles.scss
Labels: Growth & Engagement

#1575 Add set password and set recovery question logic
  backend/src/main/java/gov/cdc/usds/simplereport/api/apiuser/UserAccountCreationController.java
  backend/src/main/java/gov/cdc/usds/simplereport/api/model/errors/InvalidActivationLinkException.java
  backend/src/main/java/gov/cdc/usds/simplereport/api/model/errors/OktaAuthenticationFailureException.java
  backend/src/main/java/gov/cdc/usds/simplereport/api/model/useraccountcreation/RequestConstants.java
  backend/src/main/java/gov/cdc/usds/simplereport/api/model/useraccountcreation/SetRecoveryQuestionRequest.java
  backend/src/main/java/gov/cdc/usds/simplereport/api/model/useraccountcreation/UserAccountCreationRequest.java
  backend/src/main/java/gov/cdc/usds/simplereport/config/BeanProfiles.java
  backend/src/main/java/gov/cdc/usds/simplereport/idp/authentication/DemoOktaAuthentication.java
  backend/src/main/java/gov/cdc/usds/simplereport/idp/authentication/LiveOktaAuthentication.java
  backend/src/main/java/gov/cdc/usds/simplereport/idp/authentication/OktaAuthentication.java
  backend/src/main/resources/application-azure-demo.yaml
  backend/src/main/resources/application-azure-training.yaml
  backend/src/main/resources/application-dev.yaml
  backend/src/main/resources/application.yaml
  backend/src/test/java/gov/cdc/usds/simplereport/api/UserAccountCreationControllerTest.java
  backend/src/test/java/gov/cdc/usds/simplereport/idp/authentication/DemoOktaAuthenticationTest.java
  backend/src/test/resources/application-default.yaml
Labels: Growth & Engagement

#1652 Eliminate direct slack alerts from all environments.
  ops/demo/alerts.tf
  ops/dev/alerts.tf
  ops/prod/alerts.tf
  ops/stg/alerts.tf
  ops/test/alerts.tf
  ops/training/alerts.tf
Labels: DevOps

#1456 Workflow shenanigans
  .github/actions/deploy-front-end/action.yml
  .github/workflows/deployDemo.yml
  .github/workflows/deployDev.yml
  .github/workflows/deployPentest.yml
  .github/workflows/deployProd.yml
  .github/workflows/deployStg.yml
  .github/workflows/deployTest.yml
  .github/workflows/deployTraining.yml
  .github/workflows/terraform_checks.yml
  .github/workflows/test.yml
Labels: DevOps

#1698 Add support link
  frontend/src/app/__snapshots__/App.test.tsx.snap
  frontend/src/app/commonComponents/Header.tsx
  frontend/src/app/commonComponents/__test__/Header.test.tsx
  frontend/src/scss/PrimeStyles.scss
Labels: Growth & Engagement

#1710 Release to staging on pre-release instead of cron.
  .github/workflows/deployStg.yml
Labels: DevOps, Growth & Engagement

#1741 HotFix: Empty string can be sent to backend via new datepicker
  backend/src/main/java/gov/cdc/usds/simplereport/api/FlexibleDateScalarType.java
  backend/src/test/java/gov/cdc/usds/simplereport/api/FlexibleDateScalarTypeTest.java
Labels: Bug

#1740 Fix timer width
  frontend/src/app/testQueue/TestTimer.scss
  frontend/src/scss/PrimeStyles.scss
Labels: Front end
