Repository CDCgov/prime-simplereport, pull requests merged in 2021-04, with the labels that each got.

#1228 Add scroll to search results dropdown
  frontend/src/scss/PrimeStyles.scss
Labels: Growth & Engagement

#1252 Fix lighthouse URL
  .github/workflows/lighthouse.yml
Labels: Growth & Engagement

#1245 Update edit patient header
  frontend/src/app/Settings/Facility/FacilityForm.tsx
  frontend/src/app/patients/AddPatient.test.tsx
  frontend/src/app/patients/AddPatient.tsx
  frontend/src/app/patients/Components/PersonForm.tsx
  frontend/src/app/patients/EditPatient.test.tsx
  frontend/src/app/patients/EditPatient.tsx
  frontend/src/app/patients/__snapshots__/EditPatient.test.tsx.snap
  frontend/src/patientApp/timeOfTest/__snapshots__/PatientFormContainer.test.tsx.snap
  frontend/src/scss/AppLayout.scss
  frontend/src/scss/PrimeStyles.scss
Labels: Growth & Engagement

#1241 Create Organization site Admin on Organization Create
  .gitignore
  README.md
  backend/src/main/java/gov/cdc/usds/simplereport/api/organization/OrganizationMutationResolver.java
  backend/src/main/resources/graphql/admin.graphqls
  backend/src/test/resources/queries/organization-create
  frontend/src/app/Settings/Facility/Components/FacilityInformation.tsx
  frontend/src/app/Settings/Facility/FacilityForm.tsx
  frontend/src/app/Settings/types.d.ts
  frontend/src/app/admin/Organization/FacilityAdmin.tsx
  frontend/src/app/admin/Organization/OrganizationForm.test.tsx
  frontend/src/app/admin/Organization/OrganizationForm.tsx
  frontend/src/app/admin/Organization/OrganizationFormContainer.tsx
  frontend/src/app/admin/Organization/OrganizationInformation.tsx
  frontend/src/app/admin/Organization/facilityAdminSchema.ts
  frontend/src/app/utils/text.ts
  start.sh
Labels: Growth & Engagement

#1286 Add second button to facility form and replace card container
  frontend/src/app/Settings/Facility/Components/ManageDevices.tsx
  frontend/src/app/Settings/Facility/Components/OrderingProvider.tsx
  frontend/src/app/Settings/Facility/FacilityForm.tsx
  frontend/src/app/Settings/Facility/ManageFacilities.tsx
  frontend/src/app/Settings/FacilityForm.test.tsx
  frontend/src/app/Settings/ManageOrganization.tsx
  frontend/src/app/Settings/Settings.tsx
  frontend/src/app/Settings/Users/CreateUserForm.tsx
  frontend/src/app/Settings/Users/DeleteUserModal.tsx
  frontend/src/app/Settings/Users/InProgressModal.tsx
  frontend/src/app/Settings/Users/ManageUsers.tsx
  frontend/src/app/Settings/Users/__snapshots__/ManageUsers.test.tsx.snap
  frontend/src/app/admin/Admin.tsx
  frontend/src/app/admin/DeviceType/DeviceTypeForm.tsx
  frontend/src/app/admin/Organization/OrganizationForm.tsx
  frontend/src/app/facilitySelect/FacilityPopup.tsx
  frontend/src/app/facilitySelect/FacilitySelect.scss
  frontend/src/app/facilitySelect/__snapshots__/FacilitySelect.test.tsx.snap
  frontend/src/app/facilitySelect/__snapshots__/WithFacility.test.tsx.snap
  frontend/src/app/patients/ManagePatients.tsx
  frontend/src/app/testQueue/QueueItem.tsx
  frontend/src/app/testQueue/TestQueue.tsx
  frontend/src/app/testQueue/__snapshots__/TestQueue.test.tsx.snap
  frontend/src/app/testQueue/addToQueue/SearchResults.tsx
  frontend/src/app/testQueue/addToQueue/__snapshots__/SearchResults.test.tsx.snap
  frontend/src/app/testResults/TestResultsList.tsx
  frontend/src/app/testResults/__snapshots__/TestResultsList.test.tsx.snap
  frontend/src/scss/App.scss
  frontend/src/scss/PrimeStyles.scss
  frontend/src/scss/components/card.scss
Labels: Growth & Engagement

#1288 Removed unused "backend" and "database" terraform directories.
  ops/services/backend/main.tf
  ops/services/backend/outputs.tf
  ops/services/backend/variables.tf
  ops/services/database/main.tf
  ops/services/database/output.tf
  ops/services/database/variables.tf
Labels: DevOps

#1272 Documentation and redundant parameters in terraform.
  ops/README.md
  ops/demo/api.tf
  ops/dev/api.tf
  ops/pentest/api.tf
  ops/prod/api.tf
  ops/services/app_service/main.tf
  ops/stg/api.tf
  ops/test/api.tf
  ops/training/api.tf
Labels: DevOps

#1332 Update form labels in Other section of Person form
  frontend/src/app/commonComponents/YesNoRadioGroup.tsx
  frontend/src/app/patients/AddPatient.test.tsx
  frontend/src/app/patients/Components/PersonForm.tsx
  frontend/src/app/patients/__snapshots__/EditPatient.test.tsx.snap
  frontend/src/app/patients/personSchema.ts
  frontend/src/patientApp/timeOfTest/__snapshots__/PatientFormContainer.test.tsx.snap
Labels: Better Data

#1302 Add facility state validation
  frontend/src/app/Settings/Facility/Components/FacilityInformation.tsx
  frontend/src/app/Settings/Facility/Components/ManageDevices.tsx
  frontend/src/app/Settings/Facility/FacilityForm.tsx
  frontend/src/app/Settings/Facility/facilitySchema.ts
  frontend/src/app/Settings/FacilityForm.test.tsx
  frontend/src/app/admin/Organization/OrganizationForm.test.tsx
  frontend/src/app/commonComponents/Dropdown.tsx
  frontend/src/app/patients/Components/.ManagePhoneNumbers.tsx.swp
  frontend/src/app/utils/state.ts
  frontend/src/config/constants.ts
Labels: Growth & Engagement

#1356 Update person form fields
  frontend/src/app/commonComponents/Required.tsx
  frontend/src/app/commonComponents/RequiredMessage.tsx
  frontend/src/app/constants/index.tsx
  frontend/src/app/patients/Components/PersonForm.tsx
  frontend/src/app/patients/__snapshots__/EditPatient.test.tsx.snap
  frontend/src/app/testQueue/AoEForm/__snapshots__/SymptomInputs.test.tsx.snap
  frontend/src/patientApp/timeOfTest/PatientFormContainer.test.tsx
  frontend/src/patientApp/timeOfTest/PatientProfile.tsx
  frontend/src/patientApp/timeOfTest/__snapshots__/AoEPatientFormContainer.test.tsx.snap
  frontend/src/patientApp/timeOfTest/__snapshots__/PatientFormContainer.test.tsx.snap
  frontend/src/patientApp/timeOfTest/__snapshots__/PatientProfile.test.tsx.snap
  frontend/src/patientApp/timeOfTest/__snapshots__/PatientProfileContainer.test.tsx.snap
Labels: Better Data

#1346 Add intro to Terms of service
  frontend/e2e/pages/patientExperience.js
  frontend/src/patientApp/GuardedRoute.test.tsx
  frontend/src/patientApp/timeOfTest/TermsOfService.tsx
  frontend/src/patientApp/timeOfTest/__snapshots__/TermsOfService.test.tsx.snap
Labels: Better Data

#1260 Timer changes based on device test length
  backend/src/main/java/gov/cdc/usds/simplereport/config/InitialSetupProperties.java
  backend/src/main/java/gov/cdc/usds/simplereport/db/model/DeviceType.java
  backend/src/main/java/gov/cdc/usds/simplereport/service/DeviceTypeService.java
  backend/src/main/java/gov/cdc/usds/simplereport/utils/DeviceTestLengthConverter.java
  backend/src/main/resources/db/changelog/db.changelog-master.yaml
  backend/src/main/resources/graphql/main.graphqls
  backend/src/test/java/gov/cdc/usds/simplereport/db/model/PersonSerializationTest.java
  backend/src/test/java/gov/cdc/usds/simplereport/db/repository/FacilityRepositoryTest.java
  backend/src/test/java/gov/cdc/usds/simplereport/service/DeviceTypeServiceTest.java
  backend/src/test/java/gov/cdc/usds/simplereport/test_util/TestDataFactory.java
  frontend/src/app/testQueue/QueueItem.test.tsx
  frontend/src/app/testQueue/QueueItem.tsx
  frontend/src/app/testQueue/TestQueue.test.tsx
  frontend/src/app/testQueue/TestQueue.tsx
  frontend/src/app/testQueue/TestTimer.test.tsx
  frontend/src/app/testQueue/TestTimer.tsx
  frontend/src/app/testQueue/__snapshots__/QueueItem.test.tsx.snap
  frontend/src/app/testQueue/__snapshots__/TestQueue.test.tsx.snap
Labels: Growth & Engagement

#1342 Refactor virtual network configuration
  ops/demo/persistent/_output.tf
  ops/demo/persistent/main.tf
  ops/demo/persistent/network.tf
  ops/dev/persistent/_output.tf
  ops/dev/persistent/main.tf
  ops/dev/persistent/network.tf
  ops/pentest/persistent/_output.tf
  ops/pentest/persistent/main.tf
  ops/pentest/persistent/network.tf
  ops/prod/persistent/_output.tf
  ops/prod/persistent/main.tf
  ops/prod/persistent/network.tf
  ops/services/bastion_host/_var.tf
  ops/services/bastion_host/main.tf
  ops/services/virtual_network/_output.tf
  ops/services/virtual_network/_var.tf
  ops/services/virtual_network/main.tf
  ops/stg/persistent/_output.tf
  ops/stg/persistent/main.tf
  ops/stg/persistent/network.tf
  ops/test/persistent/_output.tf
  ops/test/persistent/main.tf
  ops/test/persistent/network.tf
  ops/training/persistent/_output.tf
  ops/training/persistent/main.tf
  ops/training/persistent/network.tf
Labels: DevOps

#1403 Upgrade to Lighthouse v7 for GitHub Actions
  .github/workflows/lighthouse.yml
Labels: DevOps, Growth & Engagement

#1411 Update test result copy
  frontend/src/patientApp/timeOfTest/TestResult.tsx
  frontend/src/patientApp/timeOfTest/__snapshots__/TestResult.test.tsx.snap
Labels: Growth & Engagement

#1393 Okta update user privileges
  frontend/src/app/Settings/Users/ManageUsers.test.tsx
  frontend/src/app/Settings/Users/ManageUsers.tsx
  frontend/src/app/Settings/Users/ManageUsersContainer.tsx
  frontend/src/app/Settings/Users/UsersSideNav.tsx
  frontend/src/app/Settings/Users/__snapshots__/ManageUsers.test.tsx.snap
Labels: Growth & Engagement

#1426 Configure dependabot
  .github/dependabot.yml
Labels: DevOps, Security

#1294 Application service slot deployment
  .github/workflows/deployDemo.yml
  .github/workflows/deployDev.yml
  .github/workflows/deployPentest.yml
  .github/workflows/deployProd.yml
  .github/workflows/deployStg.yml
  .github/workflows/deployTest.yml
  .github/workflows/deployTraining.yml
  ops/Makefile
  ops/demo/api.tf
  ops/dev/api.tf
  ops/pentest/api.tf
  ops/prod/api.tf
  ops/services/app_service/_var.tf
  ops/services/app_service/main.tf
  ops/stg/api.tf
  ops/test/api.tf
  ops/training/api.tf
Labels: DevOps

#1453 Bandaid fixes for dependabot pull request checks.
  .github/workflows/coverity_scan.yml
  .github/workflows/terraform_checks.yml
  .github/workflows/test.yml
Labels: DevOps

#1444 Add Spring Session
  backend/src/main/resources/application.yaml
Labels: Backend, Growth & Engagement

#1428 Add create an account UI
  backend/build.gradle
  frontend/src/app/accountCreation/MfaComplete/MfaComplete.stories.tsx
  frontend/src/app/accountCreation/MfaComplete/MfaComplete.test.tsx
  frontend/src/app/accountCreation/MfaComplete/MfaComplete.tsx
  frontend/src/app/accountCreation/MfaSelect/MfaSelect.stories.tsx
  frontend/src/app/accountCreation/MfaSelect/MfaSelect.test.tsx
  frontend/src/app/accountCreation/MfaSelect/MfaSelect.tsx
  frontend/src/app/accountCreation/MfaSms/MfaSms.stories.tsx
  frontend/src/app/accountCreation/MfaSms/MfaSms.test.tsx
  frontend/src/app/accountCreation/MfaSms/MfaSms.tsx
  frontend/src/app/accountCreation/MfaSmsVerify/MfaSmsVerify.stories.tsx
  frontend/src/app/accountCreation/MfaSmsVerify/MfaSmsVerify.test.tsx
  frontend/src/app/accountCreation/MfaSmsVerify/MfaSmsVerify.tsx
  frontend/src/app/accountCreation/PasswordForm/PasswordForm.stories.tsx
  frontend/src/app/accountCreation/PasswordForm/PasswordForm.test.tsx
  frontend/src/app/accountCreation/PasswordForm/PasswordForm.tsx
  frontend/src/app/accountCreation/SecurityQuestion/SecurityQuestion.stories.tsx
  frontend/src/app/accountCreation/SecurityQuestion/SecurityQuestion.test.tsx
  frontend/src/app/accountCreation/SecurityQuestion/SecurityQuestion.tsx
  frontend/src/app/admin/Organization/PendingOrganizationsList.scss
  frontend/src/app/commonComponents/Card/Card.stories.tsx
  frontend/src/app/commonComponents/Card/Card.tsx
  frontend/src/app/commonComponents/CardBackground/CardBackground.stories.tsx
  frontend/src/app/commonComponents/CardBackground/CardBackground.tsx
  frontend/src/app/commonComponents/CardContainer/CardContainer.stories.tsx
  frontend/src/app/commonComponents/CardContainer/CardContainer.tsx
  frontend/src/app/commonComponents/Dropdown.tsx
  frontend/src/app/commonComponents/RadioGroup.tsx
  frontend/src/app/commonComponents/StepIndicator.tsx
  frontend/src/app/commonComponents/TextInput.tsx
  frontend/src/app/patients/__snapshots__/EditPatient.test.tsx.snap
  frontend/src/app/testResults/TestResultsList.scss
  frontend/src/app/utils/text.ts
  frontend/src/config/constants.ts
  frontend/src/patientApp/PatientTimeOfTestContainer.tsx
  frontend/src/patientApp/timeOfTest/__snapshots__/AoEPatientFormContainer.test.tsx.snap
  frontend/src/patientApp/timeOfTest/__snapshots__/DOB.test.tsx.snap
  frontend/src/patientApp/timeOfTest/__snapshots__/PatientFormContainer.test.tsx.snap
  frontend/src/patientApp/timeOfTest/__snapshots__/PatientProfileContainer.test.tsx.snap
  frontend/src/scss/App.scss
  frontend/src/scss/PrimeStyles.scss
  frontend/src/scss/_utilities.scss
  frontend/src/scss/components/_card.scss
  frontend/src/scss/settings/_app-settings.scss
  frontend/src/scss/settings/_uswds-theme-color.scss
  frontend/src/scss/settings/_uswds-theme-components.scss
  frontend/src/scss/settings/_uswds-theme-custom-styles.scss
  frontend/src/scss/settings/_uswds-theme-general.scss
  frontend/src/scss/settings/_uswds-theme-spacing.scss
  frontend/src/scss/settings/_uswds-theme-typography.scss
  frontend/src/scss/settings/_uswds-theme-utilities.scss
  frontend/src/stories/FacilitySelect.stories.tsx
Labels: Growth & Engagement

#1447 Fix frontend insights
  .github/actions/deploy-front-end/action.yml
  .github/workflows/deployDemo.yml
  .github/workflows/deployDev.yml
  .github/workflows/deployPentest.yml
  .github/workflows/deployProd.yml
  .github/workflows/deployStg.yml
  .github/workflows/deployTest.yml
  .github/workflows/deployTraining.yml
  frontend/.env
  frontend/.env.development
  frontend/.env.production
  frontend/src/app/AppInsights.js
Labels: DevOps, Front end
