Repository CDCgov/prime-simplereport, pull requests merged in 2021-06, with the labels that each got.

#1681 Update to `dart-sass` and use mixins at the component level
  frontend/.storybook/main.js
  frontend/craco.config.js
  frontend/package.json
  frontend/src/scss/PrimeStyles.scss
  frontend/src/scss/settings/_uswds-theme-general.scss
  frontend/yarn.lock
Labels: Growth & Engagement

#1753 Add border and shadow to DatePicker calendar
  frontend/src/scss/App.scss
  frontend/src/scss/components/_datepicker.scss
  frontend/src/stories/DatePicker.stories.tsx
Labels: Growth & Engagement

#1767 'U' -> 'UNK'
  backend/src/main/java/gov/cdc/usds/simplereport/api/model/TestEventExport.java
Labels: Better Data

#1792 Deploy entire azure environment, not just app_service.
  ops/Makefile
Labels: DevOps

#1599 Allow org user to be re-added after deletion
  backend/src/main/java/gov/cdc/usds/simplereport/api/model/errors/ConflictingUserException.java
  backend/src/main/java/gov/cdc/usds/simplereport/db/model/ApiUser.java
  backend/src/main/java/gov/cdc/usds/simplereport/db/repository/ApiUserRepository.java
  backend/src/main/java/gov/cdc/usds/simplereport/idp/repository/DemoOktaRepository.java
  backend/src/main/java/gov/cdc/usds/simplereport/idp/repository/LiveOktaRepository.java
  backend/src/main/java/gov/cdc/usds/simplereport/idp/repository/OktaRepository.java
  backend/src/main/java/gov/cdc/usds/simplereport/service/ApiUserService.java
  backend/src/test/java/gov/cdc/usds/simplereport/api/graphql/ApiUserManagementTest.java
  backend/src/test/java/gov/cdc/usds/simplereport/idp/repository/DemoOktaRepositoryTest.java
  backend/src/test/java/gov/cdc/usds/simplereport/idp/repository/LiveOktaRepositoryTest.java
  backend/src/test/java/gov/cdc/usds/simplereport/service/ApiUserServiceTest.java
Labels: Growth & Engagement

#1804 Dependency-ordering of deploys
  .github/actions/build-frontend/action.yml
  .github/actions/deploy-application/action.yml
  .github/workflows/deployDemo.yml
  .github/workflows/deployDev.yml
  .github/workflows/deployPentest.yml
  .github/workflows/deployProd.yml
  .github/workflows/deployStg.yml
  .github/workflows/deployTest.yml
  .github/workflows/deployTraining.yml
Labels: DevOps, Growth & Engagement

#1870 Add optional label story
  frontend/src/stories/Optional.stories.tsx
Labels: Growth & Engagement

#1856 Add banner story
  frontend/src/stories/USAGovBanner.stories.tsx
Labels: Growth & Engagement

#1845 Add checkbox story
  frontend/src/stories/Checkboxes.stories.tsx
Labels: Growth & Engagement

#1844 Store compiled client as release asset.
  .github/workflows/deployProd.yml
Labels: DevOps

#1877 Fixed shell script problem in production deploy script.
  .github/workflows/deployProd.yml
Labels: Bug, DevOps

#1926 Backfill `TestEventExport` test coverage
  backend/src/test/java/gov/cdc/usds/simplereport/api/model/TestEventExportTest.java
  backend/src/test/java/gov/cdc/usds/simplereport/service/DataHubUploaderServiceTest.java
  backend/src/test/java/gov/cdc/usds/simplereport/test_util/TestDataFactory.java
Labels: Backend, Better Data
